# Run: blender --background --factory-startup --python tools/gltf_channel_fixture.py
# Exports a two-bone armature with a short take as GLB through Blender's own
# glTF exporter, then writes test/assets_gltf_channel_fixture.elisa: the file's
# bytes plus each animation channel's target, path and output-accessor byte
# range as read by Python's json module.
import json
import struct
from pathlib import Path
import tempfile
import bpy

ROOT = Path(__file__).resolve().parent.parent
bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.object.armature_add(location=(0.0, 0.0, 0.0))
rig = bpy.context.object
bpy.ops.object.mode_set(mode="EDIT")
root = rig.data.edit_bones[0]
root.name = "hip"
knee = rig.data.edit_bones.new("knee")
knee.head = root.tail
knee.tail = (0.0, 0.0, 2.0)
knee.parent = root
bpy.ops.object.mode_set(mode="POSE")
scene = bpy.context.scene
scene.frame_start, scene.frame_end = 1, 6
for frame in range(1, 7):
    for index, bone in enumerate(rig.pose.bones):
        bone.rotation_mode = "QUATERNION"
        bone.rotation_quaternion = (1.0, 0.05 * frame * (index + 1), 0.0, 0.0)
        bone.location = (0.0, 0.01 * frame, 0.0)
        bone.keyframe_insert("rotation_quaternion", frame=frame)
        bone.keyframe_insert("location", frame=frame)
bpy.ops.object.mode_set(mode="OBJECT")
with tempfile.TemporaryDirectory() as temporary:
    path = Path(temporary) / "rig.glb"
    bpy.ops.export_scene.gltf(filepath=str(path), export_format="GLB", export_animations=True, export_force_sampling=True)
    data = path.read_bytes()

json_length = struct.unpack_from("<I", data, 12)[0]
document = json.loads(data[20:20 + json_length])
rows = []
for c, channel in enumerate(document["animations"][0]["channels"]):
    sampler = document["animations"][0]["samplers"][channel["sampler"]]
    accessor = document["accessors"][sampler["output"]]
    view = document["bufferViews"][accessor["bufferView"]]
    components = {"SCALAR": 1, "VEC2": 2, "VEC3": 3, "VEC4": 4, "MAT4": 16}[accessor["type"]]
    size = {5120: 1, 5121: 1, 5122: 2, 5123: 2, 5125: 4, 5126: 4}[accessor["componentType"]]
    path = {"translation": 0, "rotation": 1, "scale": 2, "weights": 3}.get(channel["target"]["path"], -1)
    offset = view.get("byteOffset", 0) + accessor.get("byteOffset", 0)
    rows.append((channel["target"]["node"], path, offset, accessor["count"] * components * size, accessor["count"], components))

lines = ["# Generated by tools/gltf_channel_fixture.py (Blender glTF exporter); do not edit.",
         "def fixture_glb() -> darray[u8]:"]
body = ", ".join(str(b) for b in data)
lines.append(f"    [{body}]")
lines.append("")
lines.append("def fixture_channel_count() -> i64:")
lines.append(f"    {len(rows)}")
lines.append("")
lines.append("# target node, path, BIN offset, byte length, count, components per channel.")
lines.append("def fixture_channels() -> darray[i64]:")
lines.append("    [" + ", ".join(str(v) for row in rows for v in row) + "]")
out = ROOT / "test" / "assets_gltf_channel_fixture.elisa"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("GLB", len(data), "bytes,", len(rows), "channels ->", out)
